### ISSUE TITLE
Error while running the example 

### ISSUE THREAD

**Issue by abhi18av** [jackrusher/sparkledriver#15]
Hi @jackrusher 

I was trying to play with the `sparkledriver` for a project and I keep running into this warning message upon running the code in the `ReadMe.md`

```sh
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[2017-09-16T06:31:38.162] java.lang.ExceptionInInitializerError
[2017-09-16T06:31:38.164] 	at com.machinepublishers.jbrowserdriver.JBrowserDriverServer.main(JBrowserDriverServer.java:81)
[2017-09-16T06:31:48.200] Caused by: org.openqa.selenium.WebDriverException: org.apache.http.impl.cookie.RFC2965Spec.<init>(boolean, [Lorg.apache.http.cookie.CommonCookieAttributeHandler;)
[2017-09-16T06:31:48.201] Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
[2017-09-16T06:31:48.203] System info: host: 'abhinavs-MacBook-Pro.local', ip: '192.168.1.4', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.4', java.version: '1.8.0_131'
[2017-09-16T06:31:48.205] Driver info: driver.version: unknown
[2017-09-16T06:31:48.206] 	at com.machinepublishers.jbrowserdriver.Util.handleException(Util.java:139)
[2017-09-16T06:31:48.206] 	at com.machinepublishers.jbrowserdriver.LaxCookieSpecProvider.create(LaxCookieSpecProvider.java:170)
[2017-09-16T06:31:48.207] 	at com.machinepublishers.jbrowserdriver.CookieStore.<clinit>(CookieStore.java:42)
[2017-09-16T06:31:48.207] 	... 1 more
[2017-09-16T06:31:48.207] Caused by: java.lang.NoSuchMethodException: org.apache.http.impl.cookie.RFC2965Spec.<init>(boolean, [Lorg.apache.http.cookie.CommonCookieAttributeHandler;)
[2017-09-16T06:31:48.208] 	at java.lang.Class.getConstructor0(Class.java:3082)
[2017-09-16T06:31:48.208] 	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
[2017-09-16T06:31:48.208] 	at com.machinepublishers.jbrowserdriver.LaxCookieSpecProvider.create(LaxCookieSpecProvider.java:95)
[2017-09-16T06:31:48.209] 	... 2 more


```

However, the code does print out the expected 
`I hope you find Clojure's combination of facilities elegant, powerful, practical and fun to use.`

And it doesn't happen again after the first call , could you please guide me how to solve this?

**Comment by abhi18av** [comment]
Here's my `project.clj`

```clojure
(defproject apply_bot "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.9.0-alpha17"]
				  [sparkledriver "0.2.0"]
				  [webica "3.0.0-beta2-clj0"]]
  :main ^:skip-aot apply-bot.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})

```

And the corresponding `JDK`

```sh
apply_bot git/master*
❯ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

```

**Comment by jackrusher** [comment]
Hi! Thanks for the report. This is a harmless warning caused by an upstream problem that I've reported to that library's maintainer.

**Comment by abhi18av** [comment]
Ah, I see. Thanks 👍

**Comment by xiongtx** [comment]
@jackrusher What library is this? Would be good to include this in the README as an FAQ until it's fixed.
